### ISSUE TITLE
Question about using PCGrad with Uncertainity based weights as discussed in the paper for CIFAR dataset

### ISSUE THREAD

**Issue by madhukiranets** [WeiChengTseng/PCGrad#11]
I was wondering how PCGrad could be used in conjunction with uncertainty-based weights. Or If I have to add scalar weights to the individual losses of each task in addition to PCGrad will the following still work,

Loss = [alpha x loss1 , beta x loss2]

where alpha and beta are weights. Will the above line add some effect due to weights added to individual losses?

**Comment by lorenmt** [comment]
Yes it will still work. I have tested in my latest project.
