### ISSUE TITLE
Can PCGrad be used in conjunction with DWA？

### ISSUE THREAD

**Issue by fuweifuvtoo** [WeiChengTseng/PCGrad#3]
hello,thanks for your work
I have a question about PCGrad and DWA
It is :Can PCGrad be used in conjunction with DWA？
if the answer is YES,
How can i apply it in the code?

**Comment by WeiChengTseng** [comment]
Hi,
I am not quite sure what the **DWA** means. Is that https://arxiv.org/pdf/2010.14838.pdf ?

**Comment by fuweifuvtoo** [comment]
I mean Dynamic Weight Average，mentioned in the "End-to-End Multi-Task Learning with Attention",

**Comment by lorenmt** [comment]
> I mean Dynamic Weight Average，mentioned in the "End-to-End Multi-Task Learning with Attention",

Yes it can.
