### ISSUE TITLE
Gradient visualization

### ISSUE THREAD

**Issue by chengjianhong** [WeiChengTseng/PCGrad#6]
@WeiChengTseng

Dear Wei-Cheng,

 Is there any way to visualize the gradient change? I want to visualize them to further illustrate the superiority.

 Best wishes,

Jianhong Cheng

**Comment by WeiChengTseng** [comment]
I think you can directly use the following code to see the scale of the gradient.
```python
for p in model.parameters():
    param_norm = p.grad.data.norm(2)
    total_norm += param_norm.item() ** 2
total_norm = total_norm ** (1. / 2)
```

**Comment by WeiChengTseng** [comment]
I close this issue since there is no follow-up information.

**Comment by baibizhe** [comment]
Dear Wei-Cheng,
Thanks for your interesting work. For example , i have two losses. How should i draw picture like Figure 1 in the paper? 

Best reagrds，
Bizhe
