### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by chengjianhong** [WeiChengTseng/PCGrad#8]
Hi, can you share your processed mnist data for me? I can't download this data baecuse it is always unavaliable to the service.

`urllib.error.HTTPError: HTTP Error 503: Service Unavailable`

**Comment by WeiChengTseng** [comment]
Hi, you can also download the dataset via this link.
https://scidm.nchc.org.tw/dataset/mnist

**Comment by chengjianhong** [comment]
OK, Thanks.

**Comment by WeiChengTseng** [comment]
since this issue is solved, I close this issue.
